# This is a basic workflow to help you get started with Actions

name: omnisci_datascience_installer_deps

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: ["ubuntu-latest", "macos-latest"]
        os: ["macos-latest"]
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: omnisci
          channels: conda-forge
          channel-priority: strict

      - name: conda info
        shell: bash -l {0}
        run: |
          conda info

      - name: install dependencies
        shell: bash -l {0}
        run: |
          conda install -y -n omnisci conda-build anaconda-client

      - name: build ibis-framework
        id: pkg_ibis
        shell: bash -l {0}
        run: |
          conda build conda-recipes/ibis-framework
          PKG_IBIS_PATH=$(ls /usr/local/miniconda/envs/omnisci/conda-bld/osx-64/ibis-framework-*.tar.bz2)
          echo "::set-output name=filename::$PKG_IBIS_PATH"

          #      - name: build holoviews
          #        id: pkg_holoviews
          #        shell: bash -l {0}
          #        run: |
          #          conda build conda-recipes/holoviews
          #          PKG_HOLOVIEWS_PATH=$(ls /usr/local/miniconda/envs/omnisci/conda-bld/noarch/holoviews-*.tar.bz2)
          #          echo "::set-output name=filename::$PKG_HOLOVIEWS_PATH"

          #      - name: build hvplot
          #        id: pkg_hvplot
          #        shell: bash -l {0}
          #        run: |
          #          conda build conda-recipes/hvplot
          #          PKG_HVPLOT_PATH=$(ls /usr/local/miniconda/envs/omnisci/conda-bld/noarch/hvplot-*.tar.bz2)
          #          echo "::set-output name=filename::$PKG_HVPLOT_PATH"

      - name: publish conda package
        shell: bash -l {0}
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        if: ${{ success() && github.event_name == 'push' }}
        run: |
          anaconda --token $ANACONDA_TOKEN upload --user quansight --label omnisci --skip-existing ${{ steps.pkg_ibis.outputs.filename }}
          # anaconda --token $ANACONDA_TOKEN upload --user xmnlab --label omnisci --skip-existing ${{ steps.pkg_holoviews.outputs.filename }}
          # anaconda --token $ANACONDA_TOKEN upload --user xmnlab --label omnisci --skip-existing ${{ steps.pkg_hvplot.outputs.filename }}
