# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 23 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # This workflow contains a single job called "build"
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: ["ubuntu-latest", "macos-latest", "windows-latest"]
          python-version: ["3.7"]
      steps:
        - uses: goanpeca/setup-miniconda@v1
          with:
            auto-update-conda: true
            python-version: ${{ matrix.python-version }}
        - name: Conda info with bash
          shell: bash -l {0}
          run: conda info
        - name: Conda list with powershell
          shell: pwsh
          run: conda list
