# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 23 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: ["ubuntu-latest", "macos-latest"]
        os: ["ubuntu-latest"]
        python-version: ["3.7"]
    steps:
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: ibis-feedstock
          channels: conda-forge
          channel-priority: strict
      - name: conda info
        shell: bash -l {0}
        run: |
          conda info
      - name: install dependencies
        shell: bash -l {0}
        run: |
          conda install -y -n ibis-feedstock \
            conda-build \
            anaconda-client \
            click \
            ruamel \
            ruamel.yaml \
            jinja2 \
            plumbum \
            pathlib

      - name: Conda list
        shell: bash -l {0}
        run: conda list

      - name: copy and prepare recipe
        shell: bash -l {0}
        run: |
          wget https://raw.githubusercontent.com/ibis-project/ibis/master/ci/recipe/meta.yaml
          export URL_ROOT="https://github.com/ibis-project/ibis/archive"
          export GIT_URL="https://github.com/ibis-project/ibis.git"
          # export URL_FILE="${URL_ROOT}/master.tar.gz"
          export IBIS_VERSION=$(conda search ibis-framework|tail -n 1|grep -o -E '[0-9]+\.[0-9]+\.[0-9]+')
          sed -i "s|url: ${URL_ROOT}/{{ version }}.tar.gz|git_url: ${GIT_URL}\n  git_rev: master|" meta.yaml
          sed -i "s|{{ version }}|${IBIS_VERSION}|" meta.yaml
          sed -i "s|number: 1|number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}|" meta.yaml

      - name: conda build
        shell: bash -l {0}
        run: |
          conda build .
      - name: publish conda package
        shell: bash -l {0}
        env: # Or as an environment variable
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        if: ${{ success() && (github.event_name == 'push' || github.event_name == 'schedule') }}
        run: |
          anaconda --token $ANACONDA_TOKEN upload --user xmnlab --label dev --skip-existing /usr/share/miniconda/envs/ibis-feedstock/conda-bld/linux-64/ibis-framework-*.tar.bz2
